# vars file for nodejs
---
nodejs_version_map:
  nodejs-v9x: '9.x'
  nodejs-v8x: '8.x'
  nodejs-v7x: '7.x'
  nodejs-v6x: '6.x'
  nodejs-v5x: '5.x'
  nodejs-v4x: '4.x'
  nodejs-v012: '0.12'
  nodejs-v010: '0.10'
  iojs-v3x: 'iojs_3.x'
  iojs-v2x: 'iojs_2.x'
  iojs-v1x: 'iojs_1.x'

nodejs_dependencies:
  - curl

nodejs_version:  nodejs-v9x
nodejs_install:  build-essential
nodejs_npm_packages: []

# Supervisor dependecies descriptions from here
supervisor:

  runtime:
    dir: /var/run/supervisor
    nodaemon: "false"
    socket: supervisord.sock
    pidfile: supervisord.pid

  config:
    dir: /etc/supervisord.d
    file: /etc/supervisord.conf
    default: /etc/default.supervisord.conf

  log:
    dir: /var/log/supervisord
    file: supervisord.log
    level: info

  http:
    file: status.ini
    port: 127.0.0.1:9001
    username: user
    password: 123

# Yarn variables descriptions
# vars file for yarn
yarn_repositories:
  - type: deb
    url: 'https://dl.yarnpkg.com/debian/ stable'
    component: main

yarn_dependencies_pre:
  - apt-transport-https

yarn_dependencies:
  - yarn

# For more information about default variables see:
# http://www.ansibleworks.com/docs/playbooks_variables.html#id26
#
# git_config:
#   color:
#     branch: auto
#     diff: auto
#     interactive: auto
#     status: auto
#   push:
#     default: matching
#  git_repositories:
#    - accept_hostkey: ...
#      bare: ...
#      clone: ...
#      depth: ...
#      dest: ...
#      force: ...
#      key_file: ...
#      recursive: ...
#      reference: ...
#      refspec: ...
#      remote: ...
#      repo: ...
#      ssh_opts: ...
#      track_submodules: ...
#      pull: ...
#      version: ...
#      mode: ...
#      owner: ...
#      group: ...
#

# apt repository
git_repo: ppa:git-core/ppa
# define package (version)
git_package: git-core
# git global configuration settings
git_config: {}
# list of repositories (http://docs.ansible.com/git_module.html)
git_repositories: []
# optional ssh private key to copy to `/etc/ssh/ssh_git.key`
# and be used as default `git_key_file`
git_key:
# optional default key file to use for git operations
git_key_file:
# optional default accept host key to use for git operations (yes | no)
git_accept_hostkey: no
# optional default update to use for git operations (yes | no)
git_pull: yes
# optional default repository mode
git_mode:
# optional default repository owner
git_owner:
# optional default repository group
git_group: